# Site settings
baseurl = "https://www.example.com"
languageCode = "en-us"
title = "Intermezzio"
theme = "hugo-highlights-theme"

# Enter your tracking code to enable Google analytics
googleAnalytics = ""

[params]

  # You can use Markdown for urls [text](//domain.tld/source)
  #
  # All icons using Fontawesom's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
  # for more icons.

  # To provide more meta data for search engings feel free to add a few informations.
  # This lines will be inserted as meta tags.
  name = "Andrew Mascillaro"
  description = "Your friendly programmer"

  # For a static site it's not possible to provide a contact form. The contact form uses
  # www.formspree.io as a proxy. The form makes a Post request to their servers to send an email
  # Visitors can send up to a 1000 emails each month
  #
  # How to setup formspree
  #
  # - set your email address under 'email' below
  # - upload the generated site to your server
  # - send a dummy email to yourself to confirm your account
  # - click the confirmation link in the email from www.formspree.io
  # - That's all. Enjoy mailing!
  email = "amascillaro@gmail.com"

  # If this param is set to true, every section gets an own background image (located at static/images)
  # to change the image you could use the param picture on every section.
  # If it's disabled you could change the background to overwrite the bg.jpg and overlay.png to set the background.
  backgroundpersection = true

  # hero Section
  [params.hero]
    type = "hero"
    title = "Welcome"
    description = "A look into [intermezzio's](https://github.com/intermezzio) coding adventures"
    buttontext = "explore"

  # about section
  [[params.block]]
    id = "about"
    type = "text"
    title = "Who am I"
    description = "My name is Andrew Mascillaro, and I am a rising freshman at Olin College of Engineering. I am from Freehold, New Jersey. My favorite programming languages are JavaScript, Java, and Python. Apart from programming, I enjoy [chess](https://lichess.org/@/intermezzio) and speed memorization."
    buttontext = "next"
    # the picture is stored at static/images/
    picture = "pic01.jpg"

  # skill section
  [[params.block]]
    id = "skills"
    type = "list"
    title = "What I do"
    description = "In my free time, I like to make interesting programs. Some of my programs include a chemistry lab calculation site, calculus-teaching site, and a blog about my chess experiences. In addition, I have worked on a team to program an autonomous research drone using ROS."
    buttontext = "next"
    # the picture is stored at static/images/
    picture = "pic02.jpg"

    [[params.block.item]]
      icon = "fa-plane"
      title = "Autonomous Drone"

    [[params.block.item]]
      icon = "fa-flask"
      title = "Lab Calculator"

    [[params.block.item]]
      icon = "fa-code"
      title = "Calculus Site"

    [[params.block.item]]
      icon = "fa-flag-checkered"
      title = "Chess Blog"

  # infos section
  [[params.block]]
    id = "infos"
    type = "text"
    title = "Employment"
    description = "As a high school student, I have interned at iCIMS for software development, where I worked on localization. This summer, I will be a TA at MIT's Beaver Works Summer Institute, teaching a class for remote sensing on drones."
    # the picture is stored at static/images/
    picture = "pic03.jpg"

#  # custom section
#  [[params.block]]
#    id = "important"
#    # to make custom section copy <theme>/layouts/partials/text.html to /layouts/partials/custom.html and edit it according to your needs.
#    type = "custom"
#    title = "Don't forget"
#    description = "Curabitur massa ante, semper at massa et, semper pellentesque velit. Duis tempor est nisi, a gravida risus malesuada eget. Nunc rutrum arcu laoreet mauris sodales vehicula. Nunc iaculis felis ac dui egestas, vel ullamcorper tellus bibendum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque lacinia sem porttitor, fringilla metus at, convallis quam. Integer convallis a justo non pellentesque."
#    # the picture is stored at static/images/
#    picture = "pic04.jpg"

  # contact form
  [[params.block]]
    id = "contact"
    type = "contact"
    title = "Contact Me"
    picture = "pic05.jpg"

    [params.block.form]
      name = "Name"
      email = "Your Email"
      message = "Your Message"
      buttontext = "send message"

  # footer section
  # this section includes last block and social icons

  [params.footer]
    enable = true

    # social icons
    [params.footer.social_list]
      enable = true

      [[params.footer.social]]
        title = "Linkedin"
        icon = "fa-linkedin"
        link = "https://www.linkedin.com/in/andrew-mascillaro-7524aa179/"

      [[params.footer.social]]
        title = "Facebook"
        icon = "fa-facebook"
        link = "https://www.facebook.com/andrew.mascillaro.7"

      [[params.footer.social]]
        title = "Lichess"
        icon = "fa-flag-checkered"
        link = "https://lichess.org/@/intermezzio"

      [[params.footer.social]]
        title = "Chess"
        icon = "fa-flag-checkered"
        link = "https://lichess.org/@/intermezzio"

      [[params.footer.social]]
        title = "Gihub"
        icon = "fa-github"
        link = "https://github.com/intermezzio"

    # copyright
    #[params.footer.copyright.notice]

      [[params.footer.copyright.notice]]
        text = "© Untitled"

      [[params.footer.copyright.notice]]
        text = "Design: [HTML5UP](//html5up.net)"

      [[params.footer.copyright.notice]]
        text = "Demo Images: [Unsplash](//unsplash.com/)"
